"""
Django settings for ligand_service project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


def load_secret(path: str | None) -> str:
    if path is None:
        raise ValueError("Path to secret is None!")
    with open(path, "r") as f:
        out = f.read().strip()
    return out


def load_int_from_env(env_var: str, default=None) -> int | None:
    val = os.environ.get(env_var, default)
    return int(val) if val is not None else None


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


RUNNING_IN_DOCKER = os.environ.get("RUNNING_IN_DOCKER") is not None
if RUNNING_IN_DOCKER:
    SECRET_KEY = load_secret(os.environ.get("DJANGO_SECRET_KEY_FILE"))
else:
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY", "please-change-this-askjndkjanasasd"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") != "False"

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "huey.contrib.djhuey",
    "tailwind",
    "theme",
    "django_prometheus",
    "widget_tweaks",
    "ligand_service",
]

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]

TAILWIND_APP_NAME = "theme"

NPM_BIN_PATH = os.environ.get(
    "NPM_BIN_PATH",
    "npm",
)

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "ligand_service.urls"

MEDIA_ROOT = BASE_DIR / "user_uploads"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ligand_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


SQL_ENGINE = os.environ.get("SQL_ENGINE", "sqlite")

if RUNNING_IN_DOCKER:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("SQL_DATABASE"),
            "USER": os.environ.get("SQL_USER"),
            "PASSWORD": load_secret(os.environ.get("SQL_PASSWORD_FILE")),
            "HOST": os.environ.get("SQL_HOST", "localhost"),
            "PORT": os.environ.get("SQL_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "sqlite3_db",
        }
    }

LOGGING = (
    {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {process:d} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "webserver_file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": "./user_uploads/django.log",
                "formatter": "verbose",
            },
        },
        "root": {
            "handlers": ["webserver_file"],
            "level": "DEBUG",
        },
    }
    if RUNNING_IN_DOCKER
    else {}
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Vienna"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if RUNNING_IN_DOCKER:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": "redis:6379/1",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


if RUNNING_IN_DOCKER:
    HUEY = {
        "huey_class": "huey.RedisHuey",
        "name": DATABASES["default"]["NAME"],
        "results": True,  # Store return values of tasks.
        "store_none": False,  # If a task returns None, do not save to results.
        "immediate": False,  # If DEBUG=True, run synchronously.
        "utc": True,  # Use UTC for all times internally.
        "connection": {
            "host": "redis",
            "port": 6379,
            "db": 0,
            "connection_pool": None,  # Definitely you should use pooling!
            # ... tons of other options, see redis-py for details.
            # huey-specific connection parameters.
            "read_timeout": 1,  # If not polling (blocking pop), use timeout.
            "url": None,  # Allow Redis config via a DSN.
        },
        "consumer": {
            "workers": 1 if os.environ.get("HUEY_PERIODIC_WORKER") != "True" else 0,
            "worker_type": "process",
            "initial_delay": 0.1,  # Smallest polling interval, same as -d.
            "backoff": 1.15,  # Exponential backoff using this rate, -b.
            "max_delay": 10.0,  # Max possible polling interval, -m.
            "scheduler_interval": 1,  # Check schedule every second, -s.
            "periodic": os.environ.get("HUEY_PERIODIC_WORKER")
            == "True",  # Enable crontab feature.
            "check_worker_health": True,  # Enable worker health checks.
            "health_check_interval": 1,  # Check worker health every second.
        },
    }
else:
    HUEY = {
        "huey_class": "huey.SqliteHuey",  # Huey implementation to use.
        "name": DATABASES["default"]["NAME"],
        "results": True,  # Store return values of tasks.
        "store_none": False,  # If a task returns None, do not save to results.
        "immediate": False,  # If DEBUG=True, run synchronously.
        "utc": True,  # Use UTC for all times internally.
        "consumer": {
            "workers": 1 if os.environ.get("HUEY_PERIODIC_WORKER") != "True" else 0,
            "worker_type": "process",
            "initial_delay": 0.1,  # Smallest polling interval, same as -d.
            "backoff": 1.15,  # Exponential backoff using this rate, -b.
            "max_delay": 10.0,  # Max possible polling interval, -m.
            "scheduler_interval": 1,  # Check schedule every second, -s.
            "periodic": os.environ.get("HUEY_PERIODIC_WORKER")
            == "True",  # Enable crontab feature.
            "check_worker_health": True,  # Enable worker health checks.
            "health_check_interval": 1,  # Check worker health every second.
        },
    }

MAX_THREADS_PER_WORKER = load_int_from_env("MAX_THREADS_PER_WORKER", 2)

DELETE_RESULTS_AFTER_N_DAYS = load_int_from_env("DELETE_RESULTS_AFTER_N_DAYS")

MAXIMUM_UPLOAD_TIME_IN_MINUTES = load_int_from_env("MAXIMUM_UPLOAD_TIME_IN_MINUTES")
MAXIMUM_UPLOAD_SIZE_IN_MB = load_int_from_env("MAXIMUM_UPLOAD_SIZE_IN_MB")
MAXIMUM_UPLOADS_IN_QUEUE = load_int_from_env("MAXIMUM_UPLOADS_IN_QUEUE")
MAXIMUM_FRAMES_PER_SIMULATION = load_int_from_env("MAXIMUM_FRAMES_PER_SIMULATION")
