# Generated by Django 5.2.4 on 2025-09-01 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPCRdbResidueAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniprot_identifier", models.CharField(max_length=12)),
                ("response_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name_VOI", models.CharField(blank=True, default=None, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("common_numbering", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Running"),
                            ("F", "Failed"),
                            ("S", "Success"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("N", "Numbering"), ("I", "Calculating interactions")],
                        max_length=1,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ligand_service.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmittedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_id", models.IntegerField()),
                ("value", models.FloatField()),
                ("name", models.CharField(blank=True, default=None, null=True)),
                (
                    "file_input",
                    models.CharField(
                        choices=[("M", "MaestroDir"), ("T", "TopTrjPair")], max_length=1
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ligand_service.submission",
                    ),
                ),
            ],
        ),
    ]
