# Generated by Django 5.2.4 on 2026-03-11 12:25

import django_prometheus.models
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPCRdbResidueAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_identifier', models.CharField(max_length=12)),
                ('response_json', models.JSONField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('GPCRdb_calls'), models.Model),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dirname', models.CharField(max_length=128)),
                ('user_key', models.CharField(max_length=32)),
                ('analysis_task_id', models.UUIDField(default=None, null=True, unique=True)),
                ('frame_count', models.IntegerField(default=None, null=True)),
                ('sim_id', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
                ('results_id', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
                ('was_deleted', models.BooleanField(default=False)),
                ('topology_file', models.FilePathField(default=None, max_length=1024, null=True, path=pathlib.PurePosixPath('/home/zcrank/pan/coral-md/web/user_uploads'))),
                ('trajectory_file', models.FilePathField(default=None, max_length=1024, null=True, path=pathlib.PurePosixPath('/home/zcrank/pan/coral-md/web/user_uploads'))),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('simulation'), models.Model),
        ),
        migrations.CreateModel(
            name='GroupAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_key', models.CharField(max_length=32)),
                ('results_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('sims', models.ManyToManyField(related_name='simulations', to='ligand_service.simulation')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('group_analysis'), models.Model),
        ),
    ]
