# Generated by Django 5.2.4 on 2025-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("N", "Numbering"),
                    ("I", "Calculating interactions"),
                    ("A", "Analysing interaction results"),
                ],
                max_length=1,
            ),
        ),
    ]
