# Generated by Django 5.2.4 on 2025-09-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0002_alter_submissiontask_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontask",
            name="task_progress_info",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
