# Generated by Django 5.2.4 on 2025-09-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0003_submissiontask_task_progress_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("path", models.FilePathField(allow_folders=True)),
                ("user_key", models.CharField(max_length=32)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
    ]
