# Generated by Django 5.2.4 on 2025-09-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0004_uploadedfiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfiles",
            name="path",
        ),
        migrations.AddField(
            model_name="uploadedfiles",
            name="dirname",
            field=models.CharField(default="fillin", max_length=128),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="uploadedfiles",
            constraint=models.UniqueConstraint(
                fields=("dirname", "user_key"), name="enforce_unique_directories"
            ),
        ),
    ]
