# Generated by Django 5.2.4 on 2025-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ligand_service",
            "0005_remove_uploadedfiles_path_uploadedfiles_dirname_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="was_run",
            field=models.BooleanField(default=False),
        ),
    ]
