# Generated by Django 5.2.4 on 2025-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0006_uploadedfiles_was_run"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfiles",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="uploadedfiles",
            name="was_run",
        ),
        migrations.AddField(
            model_name="uploadedfiles",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Not submitted"),
                    ("P", "Pending"),
                    ("R", "Running"),
                    ("F", "Failed"),
                    ("S", "Success"),
                ],
                default="U",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
