# Generated by Django 5.2.4 on 2025-09-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0007_remove_uploadedfiles_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfiles",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Not started"),
                    ("Q", "Queued"),
                    ("R", "Running"),
                    ("F", "Failed"),
                    ("S", "Success"),
                ],
                max_length=1,
            ),
        ),
    ]
