# Generated by Django 5.2.4 on 2025-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0008_alter_uploadedfiles_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfiles",
            name="status",
        ),
        migrations.AddField(
            model_name="uploadedfiles",
            name="analysis_task_id",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
