# Generated by Django 5.2.4 on 2025-10-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ligand_service", "0011_remove_uploadedfiles_results_uuid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedFiles",
            new_name="Simulation",
        ),
        migrations.RemoveField(
            model_name="submissiontask",
            name="submission",
        ),
        migrations.DeleteModel(
            name="SubmittedForm",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
        migrations.DeleteModel(
            name="SubmissionTask",
        ),
    ]
