# Generated by Django 5.2.4 on 2025-10-06 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligand_service", "0012_rename_uploadedfiles_simulation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_key", models.CharField(max_length=32)),
                ("results_id", models.UUIDField(default=uuid.uuid4, null=True)),
                (
                    "sims",
                    models.ManyToManyField(
                        related_name="simulations", to="ligand_service.simulation"
                    ),
                ),
            ],
        ),
    ]
