# Generated by Django 5.2.4 on 2025-10-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ligand_service", "0013_groupanalysis"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="simulation",
            name="enforce_unique_directories",
        ),
    ]
