# Generated by Django 5.2.4 on 2025-10-19 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligand_service", "0014_remove_simulation_enforce_unique_directories"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="sim_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
