# Generated by Django 5.2.4 on 2025-10-19 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligand_service", "0015_simulation_sim_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="analysis_task_id",
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="results_id",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="sim_id",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
