# Generated by Django 5.2.4 on 2025-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligand_service", "0016_alter_simulation_analysis_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="was_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
