# Generated by Django 5.2.4 on 2025-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand_service', '0017_simulation_was_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='frame_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
