# Generated by Django 5.2.4 on 2025-11-24 21:57

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand_service', '0021_alter_simulation_topology_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='topology_file',
            field=models.FilePathField(default=None, max_length=1024, null=True, path=pathlib.PurePosixPath('/home/zcrank/pan/dev/web/user_uploads')),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='trajectory_file',
            field=models.FilePathField(default=None, max_length=1024, null=True, path=pathlib.PurePosixPath('/home/zcrank/pan/dev/web/user_uploads')),
        ),
    ]
